sudo: required
services:
  - docker

script:
  - docker build -t learnaboutdocker/ci_travis .
  - docker images learnaboutdocker/ci_travis

before_deploy:
  - docker login -u learnaboutdocker -p Knowledge6*

deploy:
  provider: script
  script: docker push learnaboutdocker/ci_travis
  on:
    branch: master
